[package]
name = "gsheet2csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-sheets4 = "4.0.1"
structopt = "0.3.26"
tokio = { version = "1.26.0", features = ["full"] }
